YouTube votes being counted again
JavaBy/opinions-bot pull request #22
Opened 2020-09-22 21:46 UTC by wtsiamruk

2020-09-22 22:07 UTC, madhead requested changes

2020-09-22 22:07 UTC, madhead commented on src/main/kotlin/by/jprof/telegram/opinions/processors/YoutubeLinksProcessor.kt
> +            if (data.startsWith("JEP") || data.startsWith("YOUTUBE")) {
I think JEP is here by (my) mistake, isn't it?

2020-09-22 22:55 UTC, wtsiamruk commented on src/main/kotlin/by/jprof/telegram/opinions/processors/YoutubeLinksProcessor.kt
> +            if (data.startsWith("JEP") || data.startsWith("YOUTUBE")) {
Looks like that but didn't touch it without confirmation :)

2020-09-23 18:04 UTC, madhead approved these changes

2020-09-23 18:05 UTC, merged