News queue + Inside Java News Cast
JavaBy/opinions-bot pull request #38
Opened 2021-04-25 18:14 UTC by sleshJdev

2021-04-25 18:27 UTC, sleshJdev commented on inside-java/src/main/kotlin/by/jprof/telegram/opinions/insidejava/Handler.kt
> +            producers.forEach { it.produce() }
At some point in the future we could move it into separate lambdas

2021-04-25 18:54 UTC, wtsiamruk commented on news-queue/src/main/kotlin/by/jprof/telegram/opinions/news/queue/NewsQueue.kt
> +    suspend fun isProcessed(item: QueueItem<*>): Boolean? {
I believe if you add index to news-queue this filtering will work faster

2021-04-25 18:56 UTC, wtsiamruk commented on .cdk/lib/opinions-stack.ts
> +        const newsQueueTable = new dynamodb.Table(this, 'news-queue', {
Maybe we should add the business key as a secondary index here to improve the processing speed for some code?

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/SecondaryIndexes.html

2021-04-25 19:00 UTC, wtsiamruk reviewed
Besides that nothing much :)

2021-04-25 19:09 UTC, sleshJdev commented on news-queue/src/main/kotlin/by/jprof/telegram/opinions/news/queue/NewsQueue.kt
> +    suspend fun isProcessed(item: QueueItem<*>): Boolean? {
I dropped this method off as it's not used

2021-04-25 19:11 UTC, wtsiamruk approved these changes

2021-04-25 19:12 UTC, sleshJdev commented on .cdk/lib/opinions-stack.ts
> +        const newsQueueTable = new dynamodb.Table(this, 'news-queue', {
We could, but I guess it's a matter of separate PR. We have very little data so don't need to care about performance too much

2021-04-25 23:05 UTC, sleshJdev commented on publication/src/main/kotlin/by/jprof/telegram/opinions/publication/TelegramPublisher.kt
> +        publishOneNews(Event.INSIDE_JAVA_PODCAST, this::announcePodcast)
Publish one new per time. Ideally, we want to publish event only when ppl will likely read: there is no active discussion in chat(check period since the last message), at morning daily so ppl will have news to read

2021-04-25 23:06 UTC, sleshJdev commented on publication/src/main/kotlin/by/jprof/telegram/opinions/publication/TelegramPublisher.kt
> +            .sortedByDescending { it.createdAt ?: it.queuedAt }
Recent news has more priority

2021-04-25 23:07 UTC, sleshJdev commented on publication/src/main/kotlin/by/jprof/telegram/opinions/publication/TelegramPublisher.kt
> +        publishOneNews(Event.INSIDE_JAVA_PODCAST, this::announcePodcast)
+ podcast has more priority over youtube video, so check it in first order

2021-04-25 23:10 UTC, sleshJdev commented on webhook/src/main/kotlin/by/jprof/telegram/opinions/webhook/processors/YoutubeLinksProcessor.kt
> -    private fun sendVoteForVideoMessage(videoId: String, update: MessageUpdate) {
Moved to [YoutubeVoting](https://github.com/JavaBy/opinions-bot/pull/38/files#diff-10889b78fd0de3f66c1d1ccbfb05f0338680b20c0a2dd644daaaf89f7ef81964)

2021-04-27 19:05 UTC, madhead requested changes

2021-04-30 16:34 UTC, sleshJdev commented on publication/src/main/kotlin/by/jprof/telegram/opinions/publication/TelegramPublisher.kt
> +        publishOneNews(Event.INSIDE_JAVA_PODCAST, this::announcePodcast)
> Although it sounds too complicated for this bot :)
Yeah

2021-04-30 16:40 UTC, sleshJdev commented on components/build.gradle.kts
> +    api("org.apache.logging.log4j:log4j-core")
Honestly, I intentionally made these deps transitive to simplify the setup, otherwise, you have to copy and paste them into each module that depends on this one. I agree that some deps should be private especially if you build a public library but it's not the case. Having all those deps in the core module(that is the _components_ module), we unify APIs e.g. logging across the whole project which is good.

Should I apply suggested changes?

2021-04-30 16:43 UTC, sleshJdev commented on components/src/main/kotlin/by/jprof/telegram/components/dao/extensions.kt
> +fun <T : Collection<String>> T.toAttributeValue(): AttributeValue = AttributeValue.builder().ss(this).build()
Good catch, e27926665e641a1881a70d869c3f5ddd2105750b

2021-04-30 17:06 UTC, sleshJdev commented on inside-java/src/main/kotlin/by/jprof/telegram/opinions/insidejava/config/beans.kt
> +    } bind Producer::class
729ebcbd674715ef3350a9e170f9edc748830e3d

2021-04-30 17:06 UTC, sleshJdev commented on webhook/src/test/kotlin/by/jprof/telegram/opinions/webhook/processors/YoutubeLinksProcessorRegexTest.kt
> +import by.jprof.telegram.opinions.webhook.processors.YoutubeLinksProcessor.Companion.youTubeVideoId
?

2021-04-30 19:52 UTC, madhead commented on components/build.gradle.kts
> +    api("org.apache.logging.log4j:log4j-core")
No, it's ok

2021-04-30 19:54 UTC, madhead commented on webhook/src/test/kotlin/by/jprof/telegram/opinions/webhook/processors/YoutubeLinksProcessorRegexTest.kt
> +import by.jprof.telegram.opinions.webhook.processors.YoutubeLinksProcessor.Companion.youTubeVideoId
Zorkiy glaz

2021-04-30 19:55 UTC, madhead approved these changes

2021-05-02 20:51 UTC, merged